// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_List = require("rescript/lib/js/belt_List.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

var input = Fs.readFileSync("input/Week2/Year2020Day4.test.txt", "utf8").split("\n\n");

var mandatoryFields = Belt_List.fromArray([
      "byr",
      "iyr",
      "eyr",
      "hgt",
      "hcl",
      "ecl",
      "pid"
    ]);

function parse(line) {
  var chunks = line.replace(/\n/g, " ").split(" ");
  return Belt_Array.map(chunks, (function (c) {
                return c.split(":");
              }));
}

function getFieldNames(fields) {
  return Belt_List.fromArray(Belt_Array.keepMap(fields, (function (f) {
                    return Belt_Array.get(f, 0);
                  })));
}

function checkFields(fieldKeys) {
  var hasField = function (key) {
    return Belt_List.has(fieldKeys, key, (function (a, b) {
                  return a === b;
                }));
  };
  return Belt_List.every(mandatoryFields, hasField);
}

console.log(Belt_Array.keep(Belt_Array.map(Belt_Array.map(input, parse), getFieldNames), checkFields).length);

exports.input = input;
exports.mandatoryFields = mandatoryFields;
exports.parse = parse;
exports.getFieldNames = getFieldNames;
exports.checkFields = checkFields;
/* input Not a pure module */
