// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_List = require("rescript/lib/js/belt_List.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Caml_int32 = require("rescript/lib/js/caml_int32.js");

var input = Fs.readFileSync("input/Week1/Year2020Day3.test.txt", "utf8").split("\n");

var input$1 = Belt_Array.map(input, (function (s) {
        return s.split("");
      }));

var input$2 = Belt_List.fromArray(Belt_Array.map(input$1, (function (line) {
            return Belt_Array.map(line, (function (x) {
                          if (x === "#") {
                            return 1;
                          } else {
                            return 0;
                          }
                        }));
          })));

var input$3 = Belt_List.tailExn(input$2);

var mod_len = Belt_List.headExn(input$3).length;

var param = Belt_List.reduce(input$3, [
      0,
      3
    ], (function (param, item) {
        var index = param[1];
        var total = param[0];
        var x = Caml_int32.mod_(index, mod_len);
        if (item.length !== 0) {
          return [
                  total + Belt_Array.getExn(item, x) | 0,
                  index + 3 | 0
                ];
        } else {
          return [
                  total,
                  0
                ];
        }
      }));

console.log(param[0]);

exports.input = input$3;
exports.mod_len = mod_len;
/* input Not a pure module */
