// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_List = require("rescript/lib/js/belt_List.js");

var input = Belt_List.fromArray(Fs.readFileSync("input/Week1/Year2020Day5.sample.txt", "utf8").split("\n"));

function binaryToDecimal(binaryString) {
  return Number("0b" + binaryString);
}

function replaceChars(str) {
  return str.replace(/[FL]/g, "0").replace(/[BR]/g, "1");
}

function splitPosition(chars) {
  return [
          chars.substring(0, 7),
          chars.substring(7, 10)
        ];
}

function calculateId(param) {
  return Number("0b" + param[0]) * 8 + Number("0b" + param[1]) | 0;
}

console.log(Belt_List.head(Belt_List.sort(Belt_List.map(Belt_List.map(Belt_List.map(input, replaceChars), splitPosition), calculateId), (function (a, b) {
                return b - a | 0;
              }))));

exports.input = input;
exports.binaryToDecimal = binaryToDecimal;
exports.replaceChars = replaceChars;
exports.splitPosition = splitPosition;
exports.calculateId = calculateId;
/* input Not a pure module */
