// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_List = require("rescript/lib/js/belt_List.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_SetString = require("rescript/lib/js/belt_SetString.js");

var input = Belt_List.fromArray(Fs.readFileSync("input/Week1/Year2020Day6.test.txt", "utf8").split("\n\n"));

console.log(Belt_List.reduce(Belt_List.map(input, (function (row) {
                return Belt_SetString.fromArray(Belt_Array.keep(row.split(""), (function (str) {
                                  return str !== "\n";
                                })));
              })), 0, (function (cnt, set) {
            return cnt + Belt_SetString.size(set) | 0;
          })));

exports.input = input;
/* input Not a pure module */
