// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_List = require("rescript/lib/js/belt_List.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

var input = Belt_List.fromArray(Fs.readFileSync("input/Week1/Year2020Day6.test.txt", "utf8").split("\n\n"));

function getAsciiStringByRange(startString, endString) {
  var start = startString.charCodeAt(0) | 0;
  var end = endString.charCodeAt(0) | 0;
  return Belt_List.map(Belt_List.fromArray(Belt_Array.range(start, end)), (function (prim) {
                return String.fromCharCode(prim);
              }));
}

var alphabetRange = getAsciiStringByRange("a", "z");

function id(x) {
  return x;
}

function markMatchingChars(row) {
  var rows = row.split("\n");
  var x = Belt_List.map(alphabetRange, (function ($$char) {
          return Belt_Array.every(rows, (function (row) {
                        return row.includes($$char);
                      }));
        }));
  return Belt_List.length(Belt_List.keep(x, id));
}

console.log(Belt_List.reduce(Belt_List.map(input, markMatchingChars), 0, (function (cnt, t) {
            return cnt + t | 0;
          })));

exports.input = input;
exports.getAsciiStringByRange = getAsciiStringByRange;
exports.alphabetRange = alphabetRange;
exports.id = id;
exports.markMatchingChars = markMatchingChars;
/* input Not a pure module */
